spring:
  datasource:
    url: jdbc:h2:file:./target/db/pass;AUTOCOMMIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    name: jdbc/pass
  jpa:
    hibernate:
      ddl-auto: update
